[package]
name = "skreen"
version = "3.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.120"
js-sys = "0.3.98"
png = "0.18.1"
base64 = "0.22"
percent-encoding = "2"

blitz-html               = { version = "0.3.0-alpha.4" }
blitz-dom                = { version = "0.3.0-alpha.4", default-features = false, features = ["svg", "woff"] }
blitz-paint              = { version = "0.3.0-alpha.4" }
blitz-traits             = { version = "0.3.0-alpha.4" }
linebender_resource_handle = "0.1.1"
parley                   = { version = "0.9", default-features = false, features = ["std"] }
anyrender           = "0.10"
anyrender_vello_cpu = "0.12"
peniko = "0.6"
kurbo = "0.13"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"