// Auto-generated by build.ts — do not edit manually
import * as wasm from "./skreen_bg.wasm";

let cachedUint8ArrayMemory0 = null;
function getUint8ArrayMemory0() {
    if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
        cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachedUint8ArrayMemory0;
}

const cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
cachedTextDecoder.decode();
function decodeText(ptr, len) {
    return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));
}

function getStringFromWasm0(ptr, len) {
    return decodeText(ptr >>> 0, len);
}

function getArrayU8FromWasm0(ptr, len) {
    ptr = ptr >>> 0;
    return getUint8ArrayMemory0().subarray(ptr / 1, ptr / 1 + len);
}

export function __wbg___wbindgen_throw_1506f2235d1bdba0(arg0, arg1) {
            throw new Error(getStringFromWasm0(arg0, arg1));
        }

export function __wbg_get_unchecked_33f6e5c9e2f2d6b2(arg0, arg1) {
            const ret = arg0[arg1 >>> 0];
            return ret;
        }

export function __wbg_length_4a591ecaa01354d9(arg0) {
            const ret = arg0.length;
            return ret;
        }

export function __wbg_length_66f1a4b2e9026940(arg0) {
            const ret = arg0.length;
            return ret;
        }

export function __wbg_prototypesetcall_3249fc62a0fafa30(arg0, arg1, arg2) {
            Uint8Array.prototype.set.call(getArrayU8FromWasm0(arg0, arg1), arg2);
        }

export function __wbindgen_init_externref_table() {
            const table = wasm.__wbindgen_externrefs;
            const offset = table.grow(4);
            table.set(0, undefined);
            table.set(offset + 0, undefined);
            table.set(offset + 1, null);
            table.set(offset + 2, true);
            table.set(offset + 3, false);
        }
