name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          cache: true

      - name: Setup Rust
        if: startsWith(github.ref, 'refs/tags/')
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: >-
            wasm32-unknown-unknown,
            aarch64-apple-darwin,
            x86_64-apple-darwin,
            x86_64-unknown-linux-gnu,
            aarch64-unknown-linux-gnu

      - name: Setup Zig
        if: startsWith(github.ref, 'refs/tags/')
        uses: mlugg/setup-zig@v2

      - name: Cache Rust
        if: startsWith(github.ref, 'refs/tags/')
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            pdf-bin -> target

      - name: Install cargo-binstall
        if: startsWith(github.ref, 'refs/tags/')
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo tools
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo binstall --no-confirm --locked wasm-bindgen-cli cargo-zigbuild

      - name: Install
        run: deno install

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: deno task build

      - name: Format
        run: deno task fmt:chk

      - name: Lint
        run: deno lint

      - name: Typecheck
        run: deno check mod.ts

      - name: Test
        run: deno task test

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          jq --arg v "$VERSION" '.version = $v' deno.jsonc > deno.tmp.jsonc && mv deno.tmp.jsonc deno.jsonc
          deno publish --allow-dirty
